name: 'Push'

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

permissions:
  contents: 'read'

concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: "${{ github.ref != 'refs/heads/main' }}"

jobs:
  PushLint:
    uses: './.github/workflows/push-lint.yaml'
    permissions:
      contents: 'read'

  PushPrettier:
    uses: './.github/workflows/push-prettier.yaml'
    permissions:
      contents: 'read'

  PushTest:
    uses: './.github/workflows/push-test.yaml'
    permissions:
      contents: 'read'

  PushWranglerBuild:
    uses: './.github/workflows/push-wrangler-build.yaml'
    permissions:
      contents: 'read'